[build]
  publish = "dist"
  command = "echo 'Pre-built locally, skipping Netlify build step.'"

[[redirects]]
  from = "/api/*"
  to = "https://api.thechasix.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/webhook/stripe"
  to = "https://api.thechasix.com/webhook/stripe"
  status = 200
  force = true
