"""Stock Watchlist endpoint backed by the committed WatchList output files.

Serves the pre-computed merged watchlist (data/watchlist/watchlist.csv) and its
schema-v3 column guide (data/watchlist/column_guide.json) verbatim. Both files
are generated by the WatchList ``marketdata`` pipeline and copied in via
``marketdata.sync_to_chasix``; nothing here is computed at request time. Loaded
once at module import.

The merged table has a ``Type`` column (Stock/ETF) and ``Sector`` metadata, so
the endpoint can filter by asset type and search ticker/sector without touching
the data pipeline.
"""

import csv
import json
import logging
from pathlib import Path

from fastapi import APIRouter, HTTPException

from src.config import DATA_DIR

logger = logging.getLogger(__name__)

router = APIRouter()

WATCHLIST_DIR = DATA_DIR / "watchlist"
WATCHLIST_CSV = WATCHLIST_DIR / "watchlist.csv"
GUIDE_JSON = WATCHLIST_DIR / "column_guide.json"

# type= query value -> value of the CSV `Type` column (None = no filter).
_TYPE_ALIASES = {
    "all": None,
    "stocks": "Stock",
    "stock": "Stock",
    "etfs": "ETF",
    "etf": "ETF",
}


def _as_number(value: str):
    """Best-effort numeric conversion for CSV string cells (keeps text as-is)."""
    try:
        return float(value)
    except (TypeError, ValueError):
        return value


def _load_rows() -> list[dict]:
    with open(WATCHLIST_CSV, encoding="utf-8", newline="") as fh:
        return [{k: _as_number(v) for k, v in row.items()} for row in csv.DictReader(fh)]


def _load_guide() -> dict:
    with open(GUIDE_JSON, encoding="utf-8") as fh:
        return json.load(fh)


_ROWS = _load_rows()
_GUIDE = _load_guide()
_COLUMNS = _GUIDE["columns"]
_AS_OF = max((r.get("Date", "") for r in _ROWS if r.get("Date")), default="")

logger.info(
    "Loaded watchlist: %d rows, %d columns, as_of=%s",
    len(_ROWS),
    len(_COLUMNS),
    _AS_OF,
)


def _filter_rows(rows: list[dict], rows_type: str | None, q: str | None) -> list[dict]:
    """Apply the asset-type filter and optional ticker/sector search."""
    if rows_type:
        rows = [r for r in rows if r.get("Type") == rows_type]
    if q:
        needle = q.strip().lower()
        if needle:
            rows = [
                r
                for r in rows
                if needle in str(r.get("Ticker", "")).lower()
                or needle in str(r.get("Sector", "")).lower()
            ]
    return rows


@router.get("")
async def get_watchlist(
    type: str | None = None,
    q: str | None = None,
    view: str | None = None,
    limit: int | None = None,
    offset: int = 0,
) -> dict:
    """Return the stock watchlist rows.

    Query params:
        type: asset-type filter - `stocks`, `etfs` (or `all`, the default).
        q: optional search - case-insensitive substring against Ticker/Sector.
        view: accepted for forward compatibility with named column views, but
            unused in v1 (phase 4).
        limit: max number of rows (default all)
        offset: number of rows to skip
    """
    if limit is not None and limit < 0:
        raise HTTPException(status_code=400, detail="limit must be >= 0")
    if offset < 0:
        raise HTTPException(status_code=400, detail="offset must be >= 0")

    rows_type = _TYPE_ALIASES.get((type or "all").strip().lower())
    if (type or "all").strip().lower() not in _TYPE_ALIASES:
        raise HTTPException(
            status_code=422,
            detail="type must be one of: stocks, etfs, all",
        )

    filtered = _filter_rows(_ROWS, rows_type, q)
    count_before_paging = len(filtered)
    rows = filtered[offset:]
    if limit is not None:
        rows = rows[:limit]
    return {
        "count": len(rows),
        "total": count_before_paging,
        "as_of": _AS_OF,
        "type": (type or "all").strip().lower() or "all",
        "columns": _COLUMNS,
        "items": rows,
    }


@router.get("/guide")
async def get_watchlist_guide() -> dict:
    """Return schema-v3 per-column metadata (label, formula, meaning, view tags)."""
    return _GUIDE