"""Stock Watchlist endpoint backed by the committed WatchList output files.

Serves the pre-computed watchlist (data/watchlist/watchlist.csv) and its
column guide (data/watchlist/column_guide.json) verbatim. Both files are
generated by the WatchList project and copied in manually; nothing here is
computed at request time. Loaded once at module import.
"""

import csv
import json
import logging
from pathlib import Path

from fastapi import APIRouter

from src.config import DATA_DIR

logger = logging.getLogger(__name__)

router = APIRouter()

WATCHLIST_DIR = DATA_DIR / "watchlist"
WATCHLIST_CSV = WATCHLIST_DIR / "watchlist.csv"
GUIDE_JSON = WATCHLIST_DIR / "column_guide.json"


def _as_number(value: str):
    """Best-effort numeric conversion for CSV string cells (keeps text as-is)."""
    try:
        return float(value)
    except (TypeError, ValueError):
        return value


def _load_rows() -> list[dict]:
    with open(WATCHLIST_CSV, encoding="utf-8", newline="") as fh:
        return [{k: _as_number(v) for k, v in row.items()} for row in csv.DictReader(fh)]


def _load_guide() -> dict:
    with open(GUIDE_JSON, encoding="utf-8") as fh:
        return json.load(fh)


_ROWS = _load_rows()
_GUIDE = _load_guide()
_COLUMNS = _GUIDE["columns"]

logger.info("Loaded watchlist: %d rows, %d columns", len(_ROWS), len(_COLUMNS))


@router.get("")
async def get_watchlist(limit: int | None = None, offset: int = 0) -> dict:
    """Return the stock watchlist rows.

    Query params:
        limit: max number of rows (default all)
        offset: number of rows to skip
    """
    rows = _ROWS[offset:]
    if limit is not None:
        rows = rows[:limit]
    return {
        "count": len(rows),
        "total": len(_ROWS),
        "as_of": _ROWS[0].get("Date", "") if _ROWS else "",
        "columns": _COLUMNS,
        "items": rows,
    }


@router.get("/guide")
async def get_watchlist_guide() -> dict:
    """Return per-column metadata (label, formula, meaning, recompute)."""
    return _GUIDE
