"""MarketHighs data importer for The ChasIX platform.

Loads the pre-computed MarketHighs output files (duration-based market
high/low deciles, sector leaderboard, and breadth aggregates) that were
generated by the MarketHighs project from 10 years of yfinance ETF history.

These files are committed to the repository at data/markethighs/ and are the
initial core dataset for Wave 1 (no external API required at runtime).
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

import pandas as pd

from src.config import DATA_DIR

logger = logging.getLogger(__name__)

MARKETHIGHS_DIR = DATA_DIR / "markethighs"
PARQUET_DIR = MARKETHIGHS_DIR / "parquet"
DETAIL_CSV = MARKETHIGHS_DIR / "detail.csv"
DETAIL_JSON = MARKETHIGHS_DIR / "detail.json"
LEADERBOARD_CSV = MARKETHIGHS_DIR / "leaderboard.csv"
BREADTH_CSV = MARKETHIGHS_DIR / "breadth.csv"

DURATIONS = ["4w", "12w", "26w", "52w"]


def load_detail(use_json: bool = True) -> pd.DataFrame:
    """Load the per-duration market high/low detail rows.

    Columns: date, ticker, sector, duration, days, recent_close,
    period_high_value, period_low_value, off_high_pct, off_low_pct,
    at_high, at_low, off_high_decile, off_low_decile.
    """
    if use_json and DETAIL_JSON.exists():
        with open(DETAIL_JSON, encoding="utf-8") as fh:
            rows = json.load(fh)
        df = pd.DataFrame(rows)
    else:
        df = pd.read_csv(DETAIL_CSV)
    df["duration"] = df["duration"].astype(str)
    df["ticker"] = df["ticker"].astype(str)
    df["sector"] = df["sector"].astype(str)
    return df


def load_leaderboard() -> pd.DataFrame:
    """Load the composite sector/ETF leaderboard.

    Columns include off_high_pct_* and high_decile_* per duration plus
    composite_score. Sorted by rank (1 = strongest market profile).
    """
    df = pd.read_csv(LEADERBOARD_CSV)
    df["ticker"] = df["ticker"].astype(str)
    df["sector"] = df["sector"].astype(str)
    df = df.sort_values("rank").reset_index(drop=True)
    return df


def load_breadth() -> pd.DataFrame:
    """Load aggregate market breadth stats per duration."""
    return pd.read_csv(BREADTH_CSV)


def get_ticker_profile(ticker: str) -> dict:
    """Return the full multi-duration profile for a single ticker.

    Returns a dict keyed by duration containing off-high/off-low percentages
    and deciles, plus the ticker metadata.
    """
    detail = load_detail()
    rows = detail[detail["ticker"] == ticker.upper()]
    if rows.empty:
        return {}
    profile = {"ticker": ticker.upper(), "sector": rows.iloc[0]["sector"], "durations": {}}
    for _, row in rows.iterrows():
        profile["durations"][row["duration"]] = {
            "days": int(row["days"]),
            "recent_close": float(row["recent_close"]),
            "period_high_value": float(row["period_high_value"]),
            "period_low_value": float(row["period_low_value"]),
            "off_high_pct": float(row["off_high_pct"]),
            "off_low_pct": float(row["off_low_pct"]),
            "at_high": bool(row["at_high"]),
            "at_low": bool(row["at_low"]),
            "off_high_decile": int(row["off_high_decile"]),
            "off_low_decile": int(row["off_low_decile"]),
        }
    return profile


def build_decile_matrix() -> pd.DataFrame:
    """Build a wide matrix (ticker x duration deciles) for similarity analysis.

    Each ticker becomes a feature vector of [off_high_decile, off_low_decile]
    across all durations — used by the recommendation engine.
    """
    detail = load_detail()
    rows = []
    for ticker, group in detail.groupby("ticker"):
        row = {"ticker": ticker}
        for _, r in group.iterrows():
            d = r["duration"]
            row[f"high_{d}"] = int(r["off_high_decile"])
            row[f"low_{d}"] = int(r["off_low_decile"])
            row[f"off_high_{d}"] = float(r["off_high_pct"])
            row[f"off_low_{d}"] = float(r["off_low_pct"])
        rows.append(row)
    return pd.DataFrame(rows).set_index("ticker")


def list_available_tickers() -> list[str]:
    """Return the set of tickers available in the parquet price files."""
    if not PARQUET_DIR.exists():
        return []
    return sorted(p.stem for p in PARQUET_DIR.glob("*.parquet"))


def load_price_history(ticker: str, limit: int = 2520) -> dict:
    """Load daily OHLCV history for a single ticker from the parquet cache.

    Files are yfinance-format: a DataFrame indexed by date with columns
    including Close, High, Low, Open, Volume. Returns the most recent `limit`
    rows as a list of dicts plus metadata. Default 2520 rows ~ 10 years.
    """
    ticker = ticker.upper()
    path = PARQUET_DIR / f"{ticker}.parquet"
    if not path.exists():
        return {}
    df = pd.read_parquet(path).reset_index()
    df.columns = [str(c).strip().lower() for c in df.columns]
    if "date" in df.columns:
        date_col = "date"
    elif df.columns[0].startswith("datetime"):
        date_col = df.columns[0]
    else:
        date_col = df.columns[0]
    # The close column is named after the ticker (yfinance-style); normalize it.
    if "close" not in df.columns and ticker.lower() in df.columns:
        df = df.rename(columns={ticker.lower(): "close"})
    df = df.sort_values(date_col).tail(limit)
    records = df.to_dict(orient="records")
    return {
        "ticker": ticker,
        "count": len(records),
        "items": records,
    }
